# Generated by Django 2.0.6 on 2018-10-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20181019_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='User',
        ),
    ]
