# Generated by Django 2.1.4 on 2019-01-04 13:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20181019_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=900),
        ),
    ]
