# Generated by Django 2.1.4 on 2019-01-04 14:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20190104_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=900),
        ),
    ]
